apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postservice
  strategy: {}
  template:
    metadata:
      labels:
        app: postservice
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: super-secret
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://postdatabase:3306/postdb?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USER
              value: root
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: EUREKA_INSTANCE_HOSTNAME
              value: registry
          image: kwetteracr.azurecr.io/postservice:latest
          imagePullPolicy: Always
          name: postservice
          ports:
            - containerPort: 8094
      imagePullSecrets:
        - name: kwettersecret
      hostname: postservice
      restartPolicy: Always
